### PR TITLE
Display parent comment when collapsed and collapse comment on tap of anywhere

### LINKED ISSUE #21: Option to not collapse parent comment in comments
**Is your feature request related to a problem? Please describe.**
Taping comments currently hides the comment tapped as well as the comments. This isn't wrong, but some other apps only collapse the replies.

**Describe the solution you'd like**
There should be an option in setting to keep the parent comment visible.

### PR DESCRIPTION
**Pull request by vbh**
Closes #21 
Also addresses #90 Closes child comments by tapping anywhere in the parent comment

### CODE REVIEW

**Comment by hjiangsu** [comment]
It looks good!

One thing though - how does this work with a single comment without any replies? Do you know what the behaviour is when you tap on a comment without replies?

**Comment by vbh** [comment]
When there are no replies, single comment will still be displayed and there is no difference on tap. Only when there are replies we collapse and open comments.

**Comment by thomasgirgenti** [comment]
Hey can we make a setting to toggle this behavior? I liked being able to fully collapse any comment.

**Comment by hjiangsu** [comment]
Definitely! Feel free to open up a new issue on GitHub for this

**Pull request merged**
