### PR TITLE
build android via docker

### PR DESCRIPTION
**Pull request by Fmstrat**
A build method using Docker. I'll be using this for dev to contribute going forward. If you would like, this could also be used for a GitHub Action for post-push compilation, but I'm not sure if that's a workflow you're looking for since you're also supporting iOS.

### CODE REVIEW

**Comment by hjiangsu** [comment]
It looks good! Thanks so much!

> GitHub Action for post-push compilation

Hmm, I'm not too familiar with this, maybe you can elaborate?

**Comment by Fmstrat** [comment]
> It looks good! Thanks so much!
> 
> > GitHub Action for post-push compilation
> 
> Hmm, I'm not too familiar with this, maybe you can elaborate?

It can be used to generate an APK and push to the releases automatically. That being said I see you have release management of some type already ;)

**Comment by hjiangsu** [comment]
Oh I see! That could be useful in the longer term. Right now, releases are somewhat manual:
- I increase the pubspec version to the correct one
- I run the `dart scripts/build.dart` file to generate the IPA/APK files
- I upload those to GitHub

I also have to generate an archive on XCode to submit to TestFlight users

If theres a way to better do that, it might help!

**Comment by Fmstrat** [comment]
Honestly the best way probably isn't to use what I'm doing locally, it's to use these popular actions from the marketplace:

The official Flutter action: https://github.com/marketplace/actions/flutter-action
Followed by create-release: https://github.com/marketplace/actions/create-release

And basically have them fire when you tag the main branch.

**Comment by hjiangsu** [comment]
Hmm yeah, I've seen them but I haven't explored them too much. I would need to figure out how they work first 😅

**Pull request merged**
