### PR TITLE
added default sorting option

### PR DESCRIPTION
**Pull request by JulianPaulus**
and here's the default sorting option :)
Screenshot_1687714324

### CODE REVIEW

**Comment by JulianPaulus** [comment]
Ah, I just saw that issue #34 exists, I'll also take a look at that.

**Comment by JulianPaulus** [comment]
That should do it!

The dropdown currently looks like this:
image

We could also change it so that it's using the same mechanism as the selector on the communities:
image

What do you think about that?

**Comment by shortwavesurfer2009** [comment]
Doing it with that sort by dialog woild keep consistancy and looks good to me at least

**Comment by hjiangsu** [comment]
Hey! Just took a quick look over it and it seems pretty good, thanks! I think for now, we can leave it as the dropdown so that we can bring out the feature a bit sooner.

However, I do agree that it makes more sense to have it be consistent with the current way we select the sort

**Pull request merged**
