### PR TITLE
Added default feed type option

### LINKED ISSUE #16: Define Thunder's default feed window
**Is your feature request related to a problem? Please describe.**
Yes, I simply want to access my subscriptions feed by default because my local feed is not quite... good?

**Describe the solution you'd like**
A function to choose the default feed in Thunder.

**Describe alternatives you've considered**
It may also be that the "default feed" is the last feed that the user left open, although it may not be intuitive at all.

**Additional context**

### PR DESCRIPTION
**Pull request by JulianPaulus**
Hi!

I added the option to select the default feed type for the main screen. This should resolve #16. I added the option to the general settings. I'm happy to take in feedback about positioning and naming!

### CODE REVIEW

**Comment by hjiangsu** [comment]
Hey, could you share a screenshot of how it looks like? Thanks so much for helping out!

**Comment by hjiangsu** [comment]
Just a heads up, I also adjusted a bit of the settings page so that theres different categories as well
- I added in a feed section to the general settings and moved theming to a different page

It would be good if the default sort type option is placed under the Feed section!

simulator_screenshot_8C125325-9D54-44C3-8AAB-E2328A43D627

**Comment by JulianPaulus** [comment]
Moved it around, here's the screenshot!
Screenshot_1687712349

**Comment by hjiangsu** [comment]
It looks good! Thanks!

**Comment by hjiangsu** [comment]
Just a quick update - i made very slight changes to the look! Just removed the underline and added some rounding to the options

simulator_screenshot_1E166B66-CBD1-4427-AB76-A315C232296F

**Comment by JulianPaulus** [comment]
Looks nice! I'm currently just also adding the same functionality for the default sorting since it'd basically the same mechanism.

I also added a constants.dart file under utils for the default definitions, since they are needed in various places.

**Pull request merged**
