### PR TITLE
Added community icons to subscribed list and search

### PR DESCRIPTION
**Pull request by CTalvio**
This adds community icons to both the side list and search.

Screenshot_20230709_030417
Screenshot_20230709_030404

### CODE REVIEW

**Comment by micahmo** [comment]
@CTalvio Just a thought... Connect shows the first letter of the community name when it doesn't have the icon. It can still be on top of a circle in the theme color, but at least it looks like something is there.

**Comment by CTalvio** [comment]
> @CTalvio Just a thought... Connect shows the first letter of the community name when it doesn't have the icon. It can still be on top of a circle in the theme color, but at least it looks like something is there.

I'll implement that. Do not merge yet.

**Comment by CTalvio** [comment]
image

Done

**Comment by micahmo** [comment]
Looks awesome!!! Should it always be uppercase or should it match the community case?

**Comment by CTalvio** [comment]
> Looks awesome!!! Should it always be uppercase or should it match the community case?

I made it always be uppercase.

**Comment by micahmo** [comment]
> I made it always be uppercase.
 Yeah I was questioning whether that was the right choice. :laughing: I don't have a strong opinion and it looks great as is. Thanks!!

**Comment by hjiangsu** [comment]
Just took a quick look and it all looks good to me! Is this ready to be merged?

**Comment by CTalvio** [comment]
> Just took a quick look and it all looks good to me! Is this ready to be merged?

It is! Go ahead.

**Pull request merged**
